version: "3.3"

services:
  database:
     image: postgres
     environment:
       - POSTGRES_DB=envio
       - POSTGRES_USER=envio_user
       - POSTGRES_PASSWORD=password
     volumes:
       - db_data:/var/lib/postgresql/data/
     ports:
       - "5432:5432"

  server:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    links:
      - database

volumes:
  db_data :
